const {test,expect}=require('@playwright/test');
const fmt=n=>Math.round(n).toLocaleString('en-US');
const summary=(page,v='JOINT_ROUTES')=>page.evaluate(v=>window[v].summary,v);
const covered=(page,v)=>page.evaluate(v=>window[v].companies.reduce((n,c)=>n+c.scenarios[0].validation.covered,0),v);
test('data, controls, coverage and map work without external network',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route(/https:\/\//,route=>route.abort());
  await page.goto('/web/');
  await expect(page.locator('#top-stats')).toContainText('209');
  await expect(page.locator('#routing')).toHaveCount(0);
  expect(await page.evaluate(()=>Object.keys(window.SAPPORO_DATA))).not.toContain('analysis');
  const js=await summary(page);
  await expect(page.locator('#top-stats')).toContainText(fmt(js.assigned_arcs));
  await expect(page.locator('#melt-tonnes')).toHaveText('201');
  // DC siting panel: factor table for every candidate, best sets follow the k selector, mesh layer toggles.
  await expect(page.locator('#siting-factors tr')).toHaveCount(7);
  await expect(page.locator('#siting-sets tr')).toHaveCount(5);
  await page.locator('#siting-k').selectOption('3');
  await expect(page.locator('#siting-sets tr').first()).toContainText('DC');
  await page.locator('#siting-sets [data-siting-set]').first().click();
  await expect(page.locator('#mesh-layer')).toBeChecked();
  expect(await page.evaluate(()=>window.DC_SITING.cells.length)).toBeGreaterThan(100);
  await expect(page.locator('#siting-factors td:nth-child(8)').first()).toContainText('%');
  await page.locator('#hazard-flood').check();
  await expect(page.locator('#hazard-flood')).toBeChecked();
  await page.locator('#recovery').fill('0');
  await page.locator('#recovery').dispatchEvent('input');
  await expect(page.locator('#melt-tonnes')).toHaveText('0');
  await page.locator('summary').filter({hasText:'協会掲載'}).click();
  await page.locator('#company-search').fill('存在しない企業名XYZ');
  await expect(page.locator('#company-count')).toHaveText('0件');
  await page.locator('#company-view').click();
  await expect(page.locator('#company-view')).toHaveClass('selected');
  await expect(page.locator('.site-card')).toHaveCount(7);
  await expect(page.locator('.dc-card')).toHaveCount(7);
  await expect(page.locator('#dc-grid-table tr')).toHaveCount(7);
  await expect(page.locator('#dc-grid-table')).toContainText('西札幌');
  await expect(page.locator('#dc-grid-table')).toContainText('山鼻');
  await expect(page.locator('#dc-grid-table')).toContainText('宮の沢');
  await expect(page.locator('.grid-ss')).toHaveCount(0);
  await page.locator('#grid-layer').check();
  expect(await page.locator('.grid-ss').count()).toBeGreaterThan(30);
  await expect(page.locator('.grid-ix')).toHaveCount(1);
  await page.locator('#grid-layer').uncheck();
  await expect(page.locator('.grid-ix')).toHaveCount(0);
  await expect(page.locator('#dc-network')).toContainText('JPNAP札幌');
  await expect(page.locator('#dc-scenarios tr')).toHaveCount(3);
  await expect(page.locator('#dc-scenarios')).toContainText('3,531');
  await page.locator('#dc-view').click();
  await expect(page.locator('.dc-marker')).toHaveCount(7);
  await page.locator('#dc-layer').uncheck();
  await expect(page.locator('.dc-marker')).toHaveCount(0);
  await page.locator('[data-dc-site="teine"]').click();
  await expect(page.locator('#dc-layer')).toBeChecked();
  await expect(page.locator('.dc-marker')).toHaveCount(7);
  await expect(page.locator('.leaflet-popup-content')).toContainText('札幌市手稲区手稲山口・前田方面');
  await expect(page.locator('.leaflet-popup-content')).toContainText('地区の代表点');
  await expect(page.locator('#weather-table tr')).toHaveCount(13);
  expect(errors).toEqual([]);
});
test('mobile layout has no horizontal document overflow',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.route(/https:\/\//,route=>route.abort());
  await page.goto('/web/');
  const sizes=await page.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth}));
  expect(sizes.body).toBeLessThanOrEqual(sizes.viewport);
});

test('wide coverage and company-origin fleet routes are selectable',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route(/https:\/\//,route=>route.abort());
  await page.goto('/web/');
  const js=await summary(page);
  await expect(page.locator('#city-stats')).toContainText(fmt(js.required_arcs));
  await expect(page.locator('#dispatch-audit')).toContainText(fmt(js.unassigned_arcs));
  await expect(page.locator('#company-map-legend')).toContainText('仮定配備による割当');
  await expect(page.locator('#dispatch-mode')).toHaveValue('joint');
  await expect(page.locator('#dispatch-audit')).toContainText(js.baseline_makespan_hours.toFixed(1));
  await expect(page.locator('#company-vehicles')).toBeDisabled();
  await page.locator('#dispatch-mode').selectOption('fixed');
  await expect(page.locator('#dispatch-mode')).toBeEnabled();
  const fs=await summary(page,'CONTRACTOR_ROUTES');
  await expect(page.locator('#dispatch-audit')).toContainText(fs.baseline_makespan_hours.toFixed(1));
  const assigned=await page.evaluate(()=>window.CONTRACTOR_ROUTES.companies.map(c=>({count:c.scenarios[0].validation.covered,other:c.scenarios.at(-1).validation.covered})));
  expect(assigned.reduce((n,c)=>n+c.count,0)).toBe(fs.assigned_arcs);
  expect(fs.assigned_arcs).toBe(js.assigned_arcs);
  expect(assigned.every(c=>c.count>1236&&c.count===c.other)).toBeTruthy();
  await page.locator('#route-company').selectOption('kashima');
  await expect(page.locator('#company-vehicles option')).toHaveCount(1);
  await expect(page.locator('#company-vehicles')).toBeDisabled();
  await expect(page.locator('#company-route-table tr')).toHaveCount(13);
  await expect(page.locator('#company-route-stats')).toContainText('市内の担当区間');
  await expect(page.locator('#company-route-table')).toContainText('シフト');
  await page.locator('#company-vehicle-focus').selectOption('2');
  await expect(page.locator('#company-map-legend')).toContainText('車両2を表示');
  await expect(page.locator('#company-map-legend .vehicle-chip[data-vehicle-chip]')).toHaveCount(13);
  await expect(page.locator('#company-map-legend .vehicle-chip[data-vehicle-chip].is-selected')).toHaveText(/車2/);
  // Selecting one shift shows only that shift; clicking it again restores every shift.
  await page.locator('#company-map-legend [data-shift-chip="1"]').first().click();
  await expect(page.locator('#company-map-legend')).toContainText('第1シフトのみ');
  await expect(page.locator('#trip-summary')).toContainText('地図は第1シフトのみ');
  expect(await page.evaluate(()=>new Set(document.querySelectorAll('#trip-table tr[data-seq]:not(.faded-row) td:nth-child(2)')).size)).toBeGreaterThan(0);
  await page.locator('.map-back-control [data-shift-chip]').click();
  await expect(page.locator('#company-map-legend')).not.toContainText('シフトのみ');
  await page.locator('#next-vehicle').click();
  await expect(page.locator('#company-vehicle-focus')).toHaveValue('3');
  await page.locator('#company-map-legend [data-vehicle-chip="1"]').click();
  await expect(page.locator('#company-vehicle-focus')).toHaveValue('1');
  await expect(page.locator('.map-back-control [data-back="vehicles"]')).toBeVisible();
  await page.locator('#map').scrollIntoViewIfNeeded();
  const scrollBefore=await page.evaluate(()=>scrollY);
  await page.locator('#map').click({position:{x:30,y:400}});
  await expect(page.locator('#company-vehicle-focus')).toHaveValue('0');
  await expect(page.locator('#trip-panel')).toBeHidden();
  expect(await page.evaluate(()=>scrollY)).toBe(scrollBefore);
  await page.locator('.map-back-control [data-back="companies"]').click();
  await expect(page.locator('#company-map-legend')).toContainText('仮定配備による割当');
  await expect(page.locator('.map-back-control')).toBeEmpty();
  await page.locator('#route-company').selectOption('kashima');
  await page.locator('#company-vehicle-focus').selectOption('1');
  await expect(page.locator('.vehicle-start.is-other')).toHaveCount(12);
  await expect(page.locator('#trip-nav .vehicle-chip')).toHaveCount(13);
  await page.locator('#city-view').click();
  const before=await page.evaluate(()=>[map.getZoom(),map.getCenter().lat,map.getCenter().lng]);
  await page.locator('.contractor-marker[title="KRS株式会社"]').hover();
  await expect(page.locator('#route-company')).toHaveValue('kashima');
  await page.locator('.contractor-marker[title="KRS株式会社"]').click();
  await expect(page.locator('#route-company')).toHaveValue('krs');
  expect(await page.evaluate(()=>[map.getZoom(),map.getCenter().lat,map.getCenter().lng])).toEqual(before);
  await expect(page.locator('#company-vehicles option')).toHaveCount(1);
  await expect(page.locator('#company-map-legend')).toContainText('破線：回送');
  await page.locator('#company-view').click();
  await expect(page.locator('.vehicle-start')).toHaveCount(3);
  await page.locator('#fit-company').click();
  await page.locator('.vehicle-start').first().click();
  expect(await page.locator('#company-vehicle-focus').inputValue()).not.toBe('0');
  await expect(page.locator('#trip-panel')).toBeVisible();
  await page.locator('#all-vehicles-view').click();
  await expect(page.locator('#trip-panel')).toBeHidden();
  await expect(page.locator('.vehicle-start')).toHaveCount(3);
  await page.locator('.vehicle-start').first().click();
  await expect(page.locator('#trip-panel')).toBeVisible();
  await page.locator('#company-vehicle-focus').selectOption('1');
  const jobs=await page.locator('#trip-table tr').count();
  expect(jobs).toBeGreaterThan(10);
  expect(await page.locator('.trip-seq').count()).toBeGreaterThan(1);
  await page.locator('[data-trip-go="3"]').click();
  expect(await page.evaluate(()=>map.getZoom())).toBeGreaterThanOrEqual(14);
  await expect(page.locator('.trip-seq')).toHaveCount(jobs);
  await expect(page.locator('#trip-table tr[data-seq="3"]')).toHaveClass(/selected-row/);
  expect(await page.locator('.route-arrow').count()).toBeGreaterThan(10);
  await expect(page.locator('#company-map-legend')).toContainText('進行方向');
  await page.locator('#trip-table tr[data-seq="4"]').click();
  await expect(page.locator('#trip-table tr[data-seq="4"]')).toHaveClass(/selected-row/);
  await expect(page.locator('#trip-table tr[data-seq="3"]')).not.toHaveClass(/selected-row/);
  await page.locator('#time-slider').fill('2');
  await expect(page.locator('#time-slider-value')).toContainText('2.0');
  await expect(page.locator('#trip-table tr.faded-row').first()).toBeVisible();
  await page.locator('#time-slider-reset').click();
  await expect(page.locator('#time-slider-value')).toHaveText('全行程');
  await page.locator('#all-companies-view').click();
  await expect(page.locator('#company-map-legend')).toContainText('仮定配備による割当');
  await page.locator('[data-company-toggle="krs"]').click();
  await expect(page.locator('[data-company-toggle="krs"]')).toHaveClass(/is-off/);
  expect(errors).toEqual([]);
});

test('numbered companies, facility toggle, reset, boundary and joint mode',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route(/https:\/\//,route=>route.abort());
  await page.goto('/web/');
  await expect(page.locator('.numbered-contractor')).toHaveCount(4);
  await expect(page.locator('.numbered-contractor')).toHaveText(['業1','業2','業3','業4']);
  await expect(page.locator('#route-company option').first()).toContainText('事業者1');
  await expect(page.locator('#boundary-layer')).toBeChecked();
  expect(await page.evaluate(()=>window.SAPPORO_BOUNDARY.companies.every(c=>c.inside_sapporo))).toBeTruthy();
  await page.locator('#melt-layer').uncheck();
  await expect(page.locator('.site-marker')).toHaveCount(0);
  await expect(page.locator('.dc-marker')).toHaveCount(7);
  await page.locator('[data-site]').first().click();
  await expect(page.locator('#melt-layer')).toBeChecked();
  await expect(page.locator('.site-marker')).toHaveCount(7);
  await expect(page.locator('#dispatch-comparison')).toContainText((await summary(page)).baseline_makespan_hours.toFixed(2));
  await expect(page.locator('#dispatch-comparison')).toContainText('選択時に読込');
  await page.locator('#route-company').selectOption('kashima');
  await page.locator('#map').click({position:{x:25,y:100}});
  await expect(page.locator('#company-map-legend')).toContainText('鹿島');
  await page.locator('#all-companies-view').click();
  await expect(page.locator('#company-map-legend')).toContainText('仮定配備による割当');
  await expect(page.locator('.numbered-contractor.is-selected')).toHaveCount(0);
  expect(await page.evaluate(()=>window.JOINT_ROUTES.route_format)).toBe('direct_jobs');
  await expect(page.locator('#company-vehicles')).toBeDisabled();
  expect(await covered(page,'JOINT_ROUTES')).toBe((await summary(page)).assigned_arcs);
  await page.locator('#route-company').selectOption('satsuichi');
  await expect(page.locator('#company-route-table tr')).toHaveCount(4);
  await page.locator('#dispatch-mode').selectOption('fixed');
  await expect(page.locator('#dispatch-mode')).toBeEnabled();
  await expect(page.locator('#dispatch-comparison')).toContainText((await summary(page,'CONTRACTOR_ROUTES')).baseline_makespan_hours.toFixed(2));
  await page.locator('#route-company').selectOption('kashima');
  await expect(page.locator('#company-vehicles')).toBeDisabled();
  await expect(page.locator('#company-route-table tr')).toHaveCount(13);
  await page.locator('#dispatch-mode').selectOption('joint');
  await expect(page.locator('#dispatch-mode')).toBeEnabled();
  await page.locator('#dispatch-mode').selectOption('fixed');
  await page.locator('#route-company').selectOption('kashima');
  await expect(page.locator('#company-vehicles')).toHaveValue('13');
  expect(errors).toEqual([]);
});
